load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "pubsub_message",
    srcs = ["pubsub_message.cc"],
    hdrs = ["pubsub_message.h"],
    visibility = ["//visibility:public"],
    deps = ["//proto:spec_cc_proto"],
)
